import Head from "next/head";
import "../styles/style.scss";
import { Toaster } from 'react-hot-toast';
import { AppProps } from 'next/app';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Xtreme Starter Next Js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Toaster />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
