import Head from "next/head";
import { Col, Row } from "reactstrap";
import SalesChart from "../src/components/dashboard/SalesChart";
import Feeds from "../src/components/dashboard/Feeds";
import ProjectTables from "../src/components/dashboard/ProjectTable";
import TopCards from "../src/components/dashboard/TopCards";
import FullLayout from "../src/layouts/FullLayout";
import bg1 from "../src/assets/images/bg/bg1.jpg";
import bg2 from "../src/assets/images/bg/bg2.jpg";
import bg3 from "../src/assets/images/bg/bg3.jpg";
import bg4 from "../src/assets/images/bg/bg4.jpg";
import useLogin from "../zustand-store/loginStore/Login";
import { useEffect } from "react";
import useAnalyticsStore from "../zustand-store/analytics/analytics";
import { useState } from "react";
import { useRouter } from "next/router";
import { StaticImageData } from "next/image";

interface BlogDataItem {
  image: StaticImageData;
  title: string;
  subtitle: string;
  description: string;
  btnbg: string;
}

const BlogData: BlogDataItem[] = [
  {
    image: bg1,
    title: "This is a simple blog",
    subtitle: "2 comments, 1 Like",
    description:
      "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
  {
    image: bg2,
    title: "Let's be simple blog",
    subtitle: "2 comments, 1 Like",
    description:
      "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
  {
    image: bg3,
    title: "Don't Lamp blog",
    subtitle: "2 comments, 1 Like",
    description:
      "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
  {
    image: bg4,
    title: "Simple is beautiful",
    subtitle: "2 comments, 1 Like",
    description:
      "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
];

const Home: React.FC = () => {
  const { getAnalytics, spanish, english, intervals, french, turkish, loading, error, total, spam, us, lang } = useAnalyticsStore();
  const [analytics, setAnalytics] = useState({});
  const { push } = useRouter();

  useEffect(() => {
    const user = JSON.parse(localStorage.getItem("loginState") || "");
    console.log(user.state.success);
    if (user.state.success === false) {
      push("/auth/login");
    }
  }, []);

  console.log("eng=> ", lang);

  useEffect(() => {
    getAnalytics();
  }, []);

  return (
    <div>
      <Head>
        <title>Xtreme Starter Next Js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <div>
        {/***Top Cards***/}
        <FullLayout>
          <Row>
            <Col sm="6" lg="3">
              <TopCards
                bg="bg-light-success text-success"
                title="News"
                subtitle="Total News"
                earning={total}
                icon="bi bi-wallet"
              />
            </Col>
            <Col sm="6" lg="3">
              <TopCards
                bg="bg-light-danger text-danger"
                title="Refunds"
                subtitle="English News"
                earning={lang}
                icon="bi bi-coin"
              />
            </Col>
            <Col sm="6" lg="3">
              <TopCards
                bg="bg-light-warning text-warning"
                title="New Project"
                subtitle="US News"
                earning={us}
                icon="bi bi-basket3"
              />
            </Col>
            <Col sm="6" lg="3">
              <TopCards
                bg="bg-light-info text-into"
                title="Sales"
                subtitle="No Spam News"
                earning={spam}
                icon="bi bi-bag"
              />
            </Col>
          </Row>
          {/***Sales & Feed***/}
          <Row>
            <Col sm="12" lg="6" xl="7" xxl="8">
              {/* passing graph analytics */}
              <SalesChart french={french} turkish={turkish} spanish={spanish} english={english} intervals={intervals} />
            </Col>
            <Col sm="12" lg="6" xl="5" xxl="4">
              <Feeds />
            </Col>
          </Row>
        </FullLayout>
      </div>
    </div>
  );
};

export default Home;
